name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Build
        run: ./ci/build-app.sh
      - name: Test
        run: ./ci/unit-test-app.sh
      - name: Nix Shell
        # You may pin to the exact commit or the version.
        # uses: workflow/nix-shell-action@6fd64e524c5e232d37f716f0437ca8d227756edd
        uses: workflow/nix-shell-action@v3.0.2
        with:
          # Interpreter to use in the nix shell shebang
          interpreter: # default is bash
          # Comma separated list of packages that are to be available in your shell
          packages: # default is bash
          # The actual script to execute in the shell
          script: ls -al && ls -al app/ 