name: hello-world
on: push
jobs:
  Clone-Down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
  Build:
      needs: Clone-Down
      - name: Build
        run: ./ci/build-app.sh
      - name: Test
        run: ./ci/unit-test-app.sh 
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .
